import './globals.css'
import type { Metadata } from 'next'
import {cn} from '../lib/utils'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons : {
        icon : '/images/favicon.ico'
    }
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={cn('min-h-screen font-sans antialiased grainy')}> 
                {children}
            </body>
        </html>
    )
}
