import './globals.css'
import type { Metadata } from 'next'
import {cn} from '../lib/utils'
import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons : {
        icon : '/images/favicon.ico'
    }
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <Providers>
                <body className={cn('min-h-screen font-sans antialiased grainy')}> 
                    <Navbar />
                    {children}
                </body>
            </Providers>
        </html>
    )
}
